In [1]:
import pandas as pd
import numpy as np
NaN = np.nan
from pyobistools.validation.check_scientificname_and_ids import check_scientificname_and_ids
import plotly.express as px
pd.set_option('max_colwidth', None)
from ckanapi import RemoteCKAN
import nest_asyncio
nest_asyncio.apply()
import requests

### Info about this notebook series

This series of notebook is meant to serve as an educational tool to learn how to use the PyObis biodiversity data validation package: + https://github.com/cioos-siooc/pyobistools

Command to install PyObis (currently not hosted on Pypi)
+ pip install git+https://github.com/cioos-siooc/pyobistools@main#egg=pyobistools

Darwin Core documentation: 
+ https://dwc.tdwg.org/

Darwin Core file types required fields: 
+ https://ioos.github.io/bio_mobilization_workshop/01-introduction/index.html
+ https://ioos.github.io/bio_mobilization_workshop/04-create-schema/index.html

### Notebook to test Pyobis' function 'check_scientifiname_and_ids'

##### Function 'check_scientifiname_and_ids' description
This function is used to evaluate the validity of scientific names, scientific name Ids and taxon ranks with Worms and Itis databases

##### Function 'check_scientifiname_and_ids' arguments
+ data: Dataframe of the data to evaluate
+ value: Type of analysis to run for each row in the dataset 
    + 'names': Analyzes scientific names validity with Worms and Itis (Itis optional)
    + 'names_ids': Above plus analyzes scientific name Ids
    + 'names_taxons_ids': Above plus analyzes taxon rank
+ itis_usage (default =  False): Option to validate data also with Itis if Worms service does not provide a positive answer for a given scientific name

Load different types of DWC files:

In [2]:
occurrence_core =      pd.read_csv('https://catalogue.preprod.ogsl.ca/data/ncc/ca-cioos_b52bb8be-d225-442c-94ab-6f107a64b8a6/saint_john_river_saltmarshes_species-occurrence_2021.csv')
occurrence_extension = pd.read_csv('https://catalogue.preprod.ogsl.ca/data/ismer/ca-cioos_0edfc94f-06d0-4823-84ef-df91e6c11fe6/ismer_occurrence_endofaune_cote-nord_2009.csv')
occurrence_extension.head(3)

,eventID,occurrenceID,scientificName,aphiaID,scientificNameID,taxonRank,occurrenceStatus,organismQuantityType,organismQuantity,basisofRecord
0,0003_Infauna_CoteNord_CamilleRobineau_BE10C1,0003_Infauna_CoteNord_CamilleRobineau_BE10C1_1,Mesodesma arctatum,156805.0,urn:lsid:marinespecies.org:taxname:156805,species,present,Individual count,2,HumanObservation
1,0003_Infauna_CoteNord_CamilleRobineau_BE10C1,0003_Infauna_CoteNord_CamilleRobineau_BE10C1_2,Nephtys ciliata,130356.0,urn:lsid:marinespecies.org:taxname:130356,species,present,Individual count,1,HumanObservation
2,0003_Infauna_CoteNord_CamilleRobineau_BE10C2,0003_Infauna_CoteNord_CamilleRobineau_BE10C2_3,Leucon nasicoides,148682.0,urn:lsid:marinespecies.org:taxname:148682,species,present,Individual count,2,HumanObservation

Try the check_scientificname_and_ids function:

In [12]:
check_scientificname_and_ids(occurrence_core, 'names').head()

15 : 200: Worms Ranunculus repens
23 : 204: Worms Hypericum perforatum
18 : 204: Worms Epalpus signifer
22 : 204: Worms Reynoutria japonica
6 : 204: Worms  sundrops
9 : 200: Worms Castor canadensis
7 : 200: Worms Elodea canadensis
8 : 204: Worms  smartweeds
5 : 200: Worms Eleocharis uniglumis
3 : 200: Worms Elymus virginicus
0 : 204: Worms Halerpestes cymbalaria
4 : 200: Worms Rosaceae
20 : 200: Worms Ulva intestinalis
11 : 204: Worms Convallaria majalis
21 : 204: Worms Hylotelephium telephium
16 : 204: Worms Persicaria maculosa
10 : 204: Worms Berberis thunbergii
29 : 204: Worms Crataegus
33 : 200: Worms Galium
34 : 204: Worms Lysimachia terrestris
32 : 200: Worms Polistes fuscatus
28 : 204: Worms Amphicarpaea bracteata
24 : 200: Worms Tussilago farfara
19 : 200: Worms Bidens
42 : 204: Worms Echinocystis lobata
26 : 200: Worms Plantago
38 : 200: Worms Centaurea jacea
2 : 200: Worms Cirsium arvense
67 : 204: Worms Acer rubrum
48 : 200: Worms Symphyotrichum
36 : 200: Worms Larus argentatus
30 : 204: Worms Stellaria graminea
12 : 200: Worms Raphanus raphanistrum
52 : 204: Worms Alnus alnobetula
17 : 200: Worms Plantago major
1 : 200: Worms Spergularia marina
43 : 204: Worms Quercus rubra
37 : 204: Worms Juncus gerardi
76 : 204: Worms Lycopus uniflorus
41 : 204: Worms Calystegia sepium
39 : 204: Worms Frangula alnus
47 : 200: Worms Liliopsida
13 : 200: Worms Juncus
50 : 204: Worms Hylaeus
35 : 204: Worms Chelone glabra
63 : 204: Worms Linaria vulgaris
53 : 204: Worms Carex pallescens
46 : 200: Worms Onoclea sensibilis
44 : 200: Worms Glyceria
58 : 204: Worms Harmonia axyridis
68 : 204: Worms Thelypteris palustris
55 : 204: Worms Stachys palustris
27 : 200: Worms Erechtites hieraciifolius
14 : 200: Worms Euthamia
31 : 200: Worms Carex
45 : 200: Worms Salix
70 : 204: Worms Thalictrum pubescens
64 : 204: Worms Alisma triviale
62 : 204: Worms Scutellaria galericulata
60 : 204: Worms Dasiphora fruticosa
71 : 204: Worms Pastinaca sativa
57 : 200: Worms Schoenoplectus tabernaemontani
56 : 200: Worms Cichorieae
72 : 204: Worms Sium suave
59 : 200: Worms Chenopodium album
65 : 204: Worms Argentina anserina
111 : 204: Worms Athyrium angustum
81 : 204: Worms Impatiens capensis
66 : 204: Worms Phalaris arundinacea
25 : 200: Worms Cichorium intybus
51 : 200: Worms Vicia
49 : 200: Worms Stuckenia pectinata
83 : 204: Worms Fraxinus pennsylvanica
78 : 200: Worms Rumex
143 : 204: Worms Cornus rugosa
89 : 204: Worms Prunella vulgaris
75 : 200: Worms Vicia cracca
107 : 204: Worms Myrica gale
54 : 200: Worms Sonchus arvensis
138 : 204: Worms Cornus sericea
86 : 204: Worms Fraxinus
69 : 204: Worms Scutellaria lateriflora
119 : 204: Worms Scirpus microcarpus
74 : 200: Worms Osmunda spectabilis
92 : 200: Worms Eutrochium maculatum
61 : 200: Worms Myriophyllum spicatum
106 : 204: Worms Acorus americanus
101 : 204: Worms Spiraea alba
102 : 204: Worms Matteuccia struthiopteris
77 : 200: Worms Typha latifolia
91 : 204: Worms Thuja occidentalis
82 : 200: Worms Cyperaceae
97 : 204: Worms Arisaema triphyllum
88 : 204: Worms Lysimachia maritima
40 : 200: Worms Leucanthemum vulgare
79 : 204: Worms Sporobolus michauxianus
117 : 204: Worms Alnus incana
85 : 200: Worms Doellingeria umbellata
84 : 200: Worms Tanacetum
100 : 204: Worms Persicaria sagittata
122 : 204: Worms Lysimachia ciliata
93 : 204: Worms Oxybasis rubra
116 : 200: Worms Poaceae
96 : 200: Worms Anthoxanthum odoratum
99 : 200: Worms Calidris minutilla
114 : 200: Worms Jacobaea vulgaris
120 : 200: Worms Osmunda claytoniana
110 : 204: Worms Euphorbia maculata
108 : 204: Worms Iris hookeri
124 : 200: Worms Agrostis gigantea
105 : 204: Worms Viburnum opulus
140 : 204: Worms Schoenoplectus pungens
87 : 204: Worms Solanum dulcamara
103 : 200: Worms Zizania
130 : 204: Worms Iris versicolor
112 : 204: Worms Rhagonycha fulva
80 : 204: Worms Hypericum mutilum
115 : 204: Worms  daisies
109 : 204: Worms Betula papyrifera
98 : 204: Worms Sorbus
144 : 204: Worms Mentha canadensis
123 : 200: Worms Cirsium
134 : 204: Worms Ilex verticillata
131 : 200: Worms Galium mollugo
133 : 200: Worms Ruppia maritima
113 : 204: Worms Apocynum cannabinum
126 : 204: Worms Persicaria amphibia
142 : 200: Worms Nuphar
135 : 200: Worms Rosa
104 : 200: Worms Senecio
137 : 200: Worms Tracheophyta
129 : 200: Worms Tanacetum vulgare
128 : 200: Worms Megaceryle alcyon
125 : 200: Worms Eleocharis palustris
132 : 200: Worms Rubus
127 : 200: Worms Scirpus
139 : 200: Worms Lythrum salicaria
118 : 200: Worms Sagittaria latifolia
94 : 200: Worms Lonicera
141 : 200: Worms Bryophyta
95 : 200: Worms Schoenoplectus
121 : 200: Worms Typha
136 : 200: Worms Centaurea nigra
90 : 200: Worms Xanthium strumarium
73 : 200: Worms Senecio viscosus

           Dataset Values  Validation Database values                        \
           scientificname Exact_Match         TaxonID Status Unacceptreason
0    Phalaris arundinacea      Non/no
109    Thuja occidentalis      Non/no
67       Rhagonycha fulva      Non/no
66       Epalpus signifer      Non/no
110        Cornus sericea      Non/no


    Taxon_Rank Valid_TaxonID Valid_Name LSID
0
109
67
66
110

In [4]:
check_scientificname_and_ids(occurrence_extension, 'names').head()

2 : 200: Worms Eteone longa
3 : 200: Worms Gammarus oceanicus
4 : 200: Worms Mya arenaria
9 : 200: Worms Leucon nasicoides
5 : 200: Worms Mytilus edulis
16 : 200: Worms Macoma balthica
7 : 200: Worms Microspio
1 : 200: Worms Nereis diversicolor
10 : 200: Worms Hydrobia minuta
13 : 200: Worms Psammonyx nobilis
8 : 200: Worms Oediceros borealis
17 : 200: Worms Idotea balthica
11 : 200: Worms Littorina obtusata
18 : 200: Worms Nephtys ciliata
6 : 200: Worms Mesodesma arctatum
14 : 200: Worms Oligochaeta
15 : 200: Worms Nematoda
12 : 200: Worms Littorina saxatilis

         Dataset Values  Validation Database values                            \
         scientificname Exact_Match         TaxonID                    Status
2     Leucon nasicoides      Non/no          148682  alternate representation
4     Psammonyx nobilis      Non/no          158140                unaccepted
8   Nereis diversicolor      Non/no          340537                   deleted
11      Hydrobia minuta      Non/no          152020                unaccepted
0    Mesodesma arctatum     Oui/Yes          156805                  accepted

                                                       \
              Unacceptreason Taxon_Rank Valid_TaxonID
2                       None    Species        110619
4   superseded recombination    Species       1255501
8       AphiaID resurrection       None        152302
11          preoccupied name    Species        574096
0                       None    Species        156805


                    Valid_Name                                       LSID
2   Leucon (Leucon) nasicoides  urn:lsid:marinespecies.org:taxname:148682
4            Wecomedon nobilis  urn:lsid:marinespecies.org:taxname:158140
8         Hediste diversicolor  urn:lsid:marinespecies.org:taxname:340537
11            Ecrobia truncata  urn:lsid:marinespecies.org:taxname:152020
0           Mesodesma arctatum  urn:lsid:marinespecies.org:taxname:156805

In [8]:
table1, table2 = check_scientificname_and_ids(occurrence_core, 'names_ids')
table1.head(3)

9 : 200: Worms Castor canadensis
16 : 204: Worms Persicaria maculosa
11 : 204: Worms Convallaria majalis
94 : 200: Worms Lonicera
81 : 204: Worms Impatiens capensis
67 : 204: Worms Acer rubrum
92 : 200: Worms Eutrochium maculatum
78 : 200: Worms Rumex
97 : 204: Worms Arisaema triphyllum
70 : 204: Worms Thalictrum pubescens
71 : 204: Worms Pastinaca sativa
75 : 200: Worms Vicia cracca
84 : 200: Worms Tanacetum
76 : 204: Worms Lycopus uniflorus
72 : 204: Worms Sium suave
91 : 204: Worms Thuja occidentalis
104 : 200: Worms Senecio
77 : 200: Worms Typha latifolia
69 : 204: Worms Scutellaria lateriflora
119 : 204: Worms Scirpus microcarpus
103 : 200: Worms Zizania
79 : 204: Worms Sporobolus michauxianus
107 : 204: Worms Myrica gale
68 : 204: Worms Thelypteris palustris
86 : 204: Worms Fraxinus
96 : 200: Worms Anthoxanthum odoratum
95 : 200: Worms Schoenoplectus
74 : 200: Worms Osmunda spectabilis
93 : 204: Worms Oxybasis rubra
90 : 200: Worms Xanthium strumarium
5 : 200: Worms Eleocharis uniglumis
3 : 200: Worms Elymus virginicus
0 : 204: Worms Halerpestes cymbalaria
14 : 200: Worms Euthamia
73 : 200: Worms Senecio viscosus
37 : 204: Worms Juncus gerardi
18 : 204: Worms Epalpus signifer
31 : 200: Worms Carex
19 : 200: Worms Bidens
17 : 200: Worms Plantago major
10 : 204: Worms Berberis thunbergii
4 : 200: Worms Rosaceae
36 : 200: Worms Larus argentatus
12 : 200: Worms Raphanus raphanistrum
20 : 200: Worms Ulva intestinalis
100 : 204: Worms Persicaria sagittata
7 : 200: Worms Elodea canadensis
101 : 204: Worms Spiraea alba
15 : 200: Worms Ranunculus repens
32 : 200: Worms Polistes fuscatus
22 : 204: Worms Reynoutria japonica
29 : 204: Worms Crataegus
8 : 204: Worms  smartweeds
35 : 204: Worms Chelone glabra
33 : 200: Worms Galium
25 : 200: Worms Cichorium intybus
24 : 200: Worms Tussilago farfara
2 : 200: Worms Cirsium arvense
27 : 200: Worms Erechtites hieraciifolius
1 : 200: Worms Spergularia marina
13 : 200: Worms Juncus
48 : 200: Worms Symphyotrichum
47 : 200: Worms Liliopsida
40 : 200: Worms Leucanthemum vulgare
39 : 204: Worms Frangula alnus
6 : 204: Worms  sundrops
34 : 204: Worms Lysimachia terrestris
23 : 204: Worms Hypericum perforatum
26 : 200: Worms Plantago
30 : 204: Worms Stellaria graminea
28 : 204: Worms Amphicarpaea bracteata
110 : 204: Worms Euphorbia maculata
45 : 200: Worms Salix
41 : 204: Worms Calystegia sepium
21 : 204: Worms Hylotelephium telephium
89 : 204: Worms Prunella vulgaris
46 : 200: Worms Onoclea sensibilis
112 : 204: Worms Rhagonycha fulva
44 : 200: Worms Glyceria
66 : 204: Worms Phalaris arundinacea
65 : 204: Worms Argentina anserina
80 : 204: Worms Hypericum mutilum
57 : 200: Worms Schoenoplectus tabernaemontani
43 : 204: Worms Quercus rubra
55 : 204: Worms Stachys palustris
134 : 204: Worms Ilex verticillata
88 : 204: Worms Lysimachia maritima
115 : 204: Worms  daisies
58 : 204: Worms Harmonia axyridis
60 : 204: Worms Dasiphora fruticosa
63 : 204: Worms Linaria vulgaris
59 : 200: Worms Chenopodium album
38 : 200: Worms Centaurea jacea
54 : 200: Worms Sonchus arvensis
61 : 200: Worms Myriophyllum spicatum
56 : 200: Worms Cichorieae
106 : 204: Worms Acorus americanus
108 : 204: Worms Iris hookeri
102 : 204: Worms Matteuccia struthiopteris
137 : 200: Worms Tracheophyta
120 : 200: Worms Osmunda claytoniana
105 : 204: Worms Viburnum opulus
87 : 204: Worms Solanum dulcamara
62 : 204: Worms Scutellaria galericulata
49 : 200: Worms Stuckenia pectinata
98 : 204: Worms Sorbus
131 : 200: Worms Galium mollugo
135 : 200: Worms Rosa
111 : 204: Worms Athyrium angustum
42 : 204: Worms Echinocystis lobata
51 : 200: Worms Vicia
83 : 204: Worms Fraxinus pennsylvanica
122 : 204: Worms Lysimachia ciliata
82 : 200: Worms Cyperaceae
53 : 204: Worms Carex pallescens
116 : 200: Worms Poaceae
114 : 200: Worms Jacobaea vulgaris
143 : 204: Worms Cornus rugosa
50 : 204: Worms Hylaeus
144 : 204: Worms Mentha canadensis
117 : 204: Worms Alnus incana
121 : 200: Worms Typha
109 : 204: Worms Betula papyrifera
118 : 200: Worms Sagittaria latifolia
52 : 204: Worms Alnus alnobetula
113 : 204: Worms Apocynum cannabinum
64 : 204: Worms Alisma triviale
124 : 200: Worms Agrostis gigantea
85 : 200: Worms Doellingeria umbellata
123 : 200: Worms Cirsium
125 : 200: Worms Eleocharis palustris
99 : 200: Worms Calidris minutilla
126 : 204: Worms Persicaria amphibia
133 : 200: Worms Ruppia maritima
140 : 204: Worms Schoenoplectus pungens
142 : 200: Worms Nuphar
130 : 204: Worms Iris versicolor
129 : 200: Worms Tanacetum vulgare
141 : 200: Worms Bryophyta
138 : 204: Worms Cornus sericea
127 : 200: Worms Scirpus
139 : 200: Worms Lythrum salicaria
128 : 200: Worms Megaceryle alcyon
132 : 200: Worms Rubus
136 : 200: Worms Centaurea nigra

           Dataset Values  Validation Database values                        \
           scientificname Exact_Match         TaxonID Status Unacceptreason
0    Phalaris arundinacea      Non/no
109    Thuja occidentalis      Non/no
67       Rhagonycha fulva      Non/no


    Taxon_Rank Valid_TaxonID Valid_Name LSID
0
109
67

In [9]:
table2.head(3)

                                  Ref. ID                Validation  \
                             OccurrenceID ScientificName_Validation
0  NCC-ST-JOHN-RIVER-SALTMARSHES-2021-001                    Non/no
1  NCC-ST-JOHN-RIVER-SALTMARSHES-2021-002                    Non/no
2  NCC-ST-JOHN-RIVER-SALTMARSHES-2021-003                    Non/no

                                        Dataset Values  \
  scientificNameID_Validation           ScientificName
0                      Non/No     Phalaris arundinacea
1                      Non/No  Sporobolus michauxianus
2                      Non/No   Schoenoplectus pungens

                                     Database values
                    ScientificNameID      Valid_Name LSID
0   urn:lsid:itis.gov:itis_tsn:41335
1                                NaN
2  urn:lsid:itis.gov:itis_tsn:508146

In [10]:
table3, table4 = check_scientificname_and_ids(occurrence_core, 'names_taxons_ids')
table3.head(3)

0 : 204: Worms Halerpestes cymbalaria
4 : 200: Worms Rosaceae
8 : 204: Worms  smartweeds
1 : 200: Worms Spergularia marina
11 : 204: Worms Convallaria majalis
3 : 200: Worms Elymus virginicus
6 : 204: Worms  sundrops
28 : 204: Worms Amphicarpaea bracteata
10 : 204: Worms Berberis thunbergii
12 : 200: Worms Raphanus raphanistrum
15 : 200: Worms Ranunculus repens
16 : 204: Worms Persicaria maculosa
13 : 200: Worms Juncus
5 : 200: Worms Eleocharis uniglumis
20 : 200: Worms Ulva intestinalis
19 : 200: Worms Bidens
2 : 200: Worms Cirsium arvense
34 : 204: Worms Lysimachia terrestris
18 : 204: Worms Epalpus signifer
21 : 204: Worms Hylotelephium telephium
93 : 204: Worms Oxybasis rubra
9 : 200: Worms Castor canadensis
26 : 200: Worms Plantago
7 : 200: Worms Elodea canadensis
22 : 204: Worms Reynoutria japonica
35 : 204: Worms Chelone glabra
37 : 204: Worms Juncus gerardi
29 : 204: Worms Crataegus
32 : 200: Worms Polistes fuscatus
25 : 200: Worms Cichorium intybus
46 : 200: Worms Onoclea sensibilis
38 : 200: Worms Centaurea jacea
23 : 204: Worms Hypericum perforatum
44 : 200: Worms Glyceria
33 : 200: Worms Galium
45 : 200: Worms Salix
24 : 200: Worms Tussilago farfara
30 : 204: Worms Stellaria graminea
43 : 204: Worms Quercus rubra
36 : 200: Worms Larus argentatus
49 : 200: Worms Stuckenia pectinata
50 : 204: Worms Hylaeus
55 : 204: Worms Stachys palustris
68 : 204: Worms Thelypteris palustris
66 : 204: Worms Phalaris arundinacea
31 : 200: Worms Carex
48 : 200: Worms Symphyotrichum
47 : 200: Worms Liliopsida
51 : 200: Worms Vicia
39 : 204: Worms Frangula alnus
69 : 204: Worms Scutellaria lateriflora
63 : 204: Worms Linaria vulgaris
40 : 200: Worms Leucanthemum vulgare
41 : 204: Worms Calystegia sepium
53 : 204: Worms Carex pallescens
54 : 200: Worms Sonchus arvensis
65 : 204: Worms Argentina anserina
110 : 204: Worms Euphorbia maculata
113 : 204: Worms Apocynum cannabinum
76 : 204: Worms Lycopus uniflorus
138 : 204: Worms Cornus sericea
135 : 200: Worms Rosa
75 : 200: Worms Vicia cracca
117 : 204: Worms Alnus incana
90 : 200: Worms Xanthium strumarium
56 : 200: Worms Cichorieae
71 : 204: Worms Pastinaca sativa
123 : 200: Worms Cirsium
118 : 200: Worms Sagittaria latifolia
64 : 204: Worms Alisma triviale
77 : 200: Worms Typha latifolia
134 : 204: Worms Ilex verticillata
84 : 200: Worms Tanacetum
97 : 204: Worms Arisaema triphyllum
98 : 204: Worms Sorbus
73 : 200: Worms Senecio viscosus
59 : 200: Worms Chenopodium album
144 : 204: Worms Mentha canadensis
52 : 204: Worms Alnus alnobetula
132 : 200: Worms Rubus
121 : 200: Worms Typha
99 : 200: Worms Calidris minutilla
62 : 204: Worms Scutellaria galericulata
108 : 204: Worms Iris hookeri
27 : 200: Worms Erechtites hieraciifolius
14 : 200: Worms Euthamia
85 : 200: Worms Doellingeria umbellata
42 : 204: Worms Echinocystis lobata
74 : 200: Worms Osmunda spectabilis
120 : 200: Worms Osmunda claytoniana
61 : 200: Worms Myriophyllum spicatum
17 : 200: Worms Plantago major
60 : 204: Worms Dasiphora fruticosa
70 : 204: Worms Thalictrum pubescens
131 : 200: Worms Galium mollugo
88 : 204: Worms Lysimachia maritima
140 : 204: Worms Schoenoplectus pungens
130 : 204: Worms Iris versicolor
127 : 200: Worms Scirpus
58 : 204: Worms Harmonia axyridis
81 : 204: Worms Impatiens capensis
89 : 204: Worms Prunella vulgaris
82 : 200: Worms Cyperaceae
100 : 204: Worms Persicaria sagittata
94 : 200: Worms Lonicera
96 : 200: Worms Anthoxanthum odoratum
86 : 204: Worms Fraxinus
109 : 204: Worms Betula papyrifera
72 : 204: Worms Sium suave
80 : 204: Worms Hypericum mutilum
107 : 204: Worms Myrica gale
79 : 204: Worms Sporobolus michauxianus
78 : 200: Worms Rumex
91 : 204: Worms Thuja occidentalis
103 : 200: Worms Zizania
95 : 200: Worms Schoenoplectus
57 : 200: Worms Schoenoplectus tabernaemontani
105 : 204: Worms Viburnum opulus
87 : 204: Worms Solanum dulcamara
67 : 204: Worms Acer rubrum
83 : 204: Worms Fraxinus pennsylvanica
129 : 200: Worms Tanacetum vulgare
106 : 204: Worms Acorus americanus
92 : 200: Worms Eutrochium maculatum
142 : 200: Worms Nuphar
126 : 204: Worms Persicaria amphibia
128 : 200: Worms Megaceryle alcyon
102 : 204: Worms Matteuccia struthiopteris
104 : 200: Worms Senecio
143 : 204: Worms Cornus rugosa
119 : 204: Worms Scirpus microcarpus
139 : 200: Worms Lythrum salicaria
114 : 200: Worms Jacobaea vulgaris
111 : 204: Worms Athyrium angustum
125 : 200: Worms Eleocharis palustris
141 : 200: Worms Bryophyta
137 : 200: Worms Tracheophyta
136 : 200: Worms Centaurea nigra
133 : 200: Worms Ruppia maritima
112 : 204: Worms Rhagonycha fulva
115 : 204: Worms  daisies
101 : 204: Worms Spiraea alba
116 : 200: Worms Poaceae
122 : 204: Worms Lysimachia ciliata
124 : 200: Worms Agrostis gigantea

           Dataset Values  Validation Database values                        \
           ScientificName Exact_Match         TaxonID Status Unacceptreason
0    Phalaris arundinacea      Non/no
109    Thuja occidentalis      Non/no
67       Rhagonycha fulva      Non/no


    Taxon_Rank Valid_TaxonID Valid_Name LSID
0
109
67

In [11]:
table4.head(3)

                                  Ref. ID                Validation  \
                             OccurrenceID ScientificName_Validation
0  NCC-ST-JOHN-RIVER-SALTMARSHES-2021-001                    Non/no
1  NCC-ST-JOHN-RIVER-SALTMARSHES-2021-002                    Non/no
2  NCC-ST-JOHN-RIVER-SALTMARSHES-2021-003                    Non/no

                                                             Dataset Values  \
  TaxonRank_Validation scientificNameID_Validation           ScientificName
0               Non/No                      Non/No     Phalaris arundinacea
1               Non/No                      Non/No  Sporobolus michauxianus
2               Non/No                      Non/No   Schoenoplectus pungens

                                               Database values
  TaxonRank                   ScientificNameID      Valid_Name Taxon_Rank LSID
0   species   urn:lsid:itis.gov:itis_tsn:41335
1   species                                NaN
2   species  urn:lsid:itis.gov:itis_tsn:508146

Try the check_scientificname_and_ids function - itis_usage:

In [ ]:
check_scientificname_and_ids(occurrence_core, 'names', itis_usage= True).head()

0 : 200: Worms Spergularia marina
1 : 204: Worms Hypericum mutilum
4 : 200: Worms Ulva intestinalis
2 : 204: Worms Acorus americanus
3 : 200: Worms Tussilago farfara
5 : 204: Worms Persicaria sagittata
6 : 200: Worms Cyperaceae
9 : 204: Worms Epalpus signifer
7 : 204: Worms Juncus gerardi
12 : 200: Worms Osmunda claytoniana
8 : 200: Worms Eleocharis palustris
11 : 204: Worms Mentha canadensis
14 : 204: Worms Thelypteris palustris
13 : 204: Worms Convallaria majalis
10 : 204: Worms Impatiens capensis
15 : 204: Worms Scutellaria galericulata
17 : 204: Worms Stachys palustris
18 : 204: Worms Alnus incana
16 : 204: Worms Pastinaca sativa
20 : 204: Worms Lysimachia terrestris
23 : 204: Worms Scirpus microcarpus
21 : 204: Worms Frangula alnus
25 : 204: Worms Linaria vulgaris
19 : 200: Worms Rosa
22 : 204: Worms Fraxinus
24 : 200: Worms Centaurea jacea
26 : 200: Worms Xanthium strumarium
28 : 200: Worms Carex
27 : 200: Worms Rubus
29 : 204: Worms Phalaris arundinacea
30 : 204: Worms Iris hookeri
31 : 200: Worms Schoenoplectus tabernaemontani
32 : 200: Worms Larus argentatus
35 : 200: Worms Bryophyta
34 : 204: Worms  daisies
37 : 204: Worms Quercus rubra
36 : 204: Worms Spiraea alba
33 : 204: Worms Stellaria graminea
38 : 200: Worms Tanacetum
44 : 200: Worms Galium mollugo
43 : 200: Worms Juncus
41 : 200: Worms Centaurea nigra
40 : 200: Worms Cichorium intybus
45 : 200: Worms Ranunculus repens
46 : 200: Worms Calidris minutilla
39 : 200: Worms Polistes fuscatus
48 : 204: Worms Thalictrum pubescens
42 : 200: Worms Tanacetum vulgare
49 : 204: Worms Hylotelephium telephium
50 : 200: Worms Rumex
47 : 200: Worms Typha latifolia
55 : 200: Worms Elodea canadensis
56 : 204: Worms Acer rubrum
53 : 200: Worms Lythrum salicaria
54 : 204: Worms Calystegia sepium
51 : 200: Worms Euthamia
57 : 204: Worms Amphicarpaea bracteata
58 : 204: Worms Harmonia axyridis
52 : 204: Worms Iris versicolor
65 : 204: Worms Apocynum cannabinum
61 : 200: Worms Jacobaea vulgaris
63 : 200: Worms Erechtites hieraciifolius
60 : 200: Worms Myriophyllum spicatum
64 : 204: Worms Athyrium angustum
59 : 204: Worms Scutellaria lateriflora
62 : 200: Worms Nuphar
67 : 204: Worms Lycopus uniflorus
66 : 200: Worms Raphanus raphanistrum
71 : 200: Worms Zizania
78 : 204: Worms Alnus alnobetula
68 : 204: Worms Lysimachia ciliata
73 : 200: Worms Bidens
77 : 204: Worms Prunella vulgaris
75 : 204: Worms Fraxinus pennsylvanica
74 : 200: Worms Galium
76 : 200: Worms Vicia cracca
69 : 204: Worms Chelone glabra
82 : 204: Worms  smartweeds
70 : 200: Worms Agrostis gigantea
80 : 204: Worms Crataegus
83 : 200: Worms Lonicera
79 : 204: Worms Halerpestes cymbalaria
81 : 200: Worms Cirsium
84 : 200: Worms Salix
85 : 204: Worms Sium suave
91 : 204: Worms Sorbus
87 : 200: Worms Castor canadensis
86 : 204: Worms Oxybasis rubra
99 : 200: Worms Osmunda spectabilis
88 : 204: Worms Dasiphora fruticosa
98 : 204: Worms Berberis thunbergii
101 : 200: Worms Vicia
90 : 204: Worms Cornus sericea
92 : 200: Worms Eutrochium maculatum
89 : 204: Worms Persicaria amphibia
0 : 200: Itis Phalaris arundinacea
3 : 200: Itis Oxybasis rubra - Empty answer
5 : 200: Itis Linaria vulgaris
11 : 200: Itis Halerpestes cymbalaria
12 : 200: Itis Dasiphora fruticosa
13 : 200: Itis Chelone glabra
22 : 200: Itis Impatiens capensis
23 : 200: Itis Stachys palustris
24 : 200: Itis Fraxinus pennsylvanica
25 : 200: Itis Sium suave
26 : 200: Itis Amphicarpaea bracteata
27 : 200: Itis Prunella vulgaris
28 : 200: Itis Berberis thunbergii
29 : 200: Itis Mentha canadensis
31 : 200: Itis Athyrium angustum
33 : 200: Itis Alnus incana
40 : 200: Itis Crataegus
46 : 200: Itis Convallaria majalis
49 : 200: Itis Alnus alnobetula
51 : 200: Itis Iris hookeri
56 : 200: Itis Calystegia sepium
59 : 200: Itis Thelypteris palustris
60 : 200: Itis Thalictrum pubescens
63 : 200: Itis Hylotelephium telephium
66 : 200: Itis Epalpus signifer
71 : 200: Itis Stellaria graminea
76 : 200: Itis Juncus gerardi
78 : 200: Itis Harmonia axyridis
80 : 200: Itis Acorus americanus
81 : 200: Itis Scirpus microcarpus
84 : 200: Itis Scutellaria lateriflora
85 : 200: Itis Frangula alnus
87 : 200: Itis  daisies - Empty answer
89 : 200: Itis Apocynum cannabinum
91 : 200: Itis Spiraea alba
92 : 200: Itis Lysimachia terrestris
93 : 200: Itis Lycopus uniflorus
96 : 200: Itis  smartweeds - Empty answer
98 : 200: Itis Scutellaria galericulata
108 : 200: Itis Persicaria amphibia
110 : 200: Itis Cornus sericea
114 : 200: Itis Pastinaca sativa
116 : 200: Itis Sorbus
121 : 200: Itis Persicaria sagittata
122 : 200: Itis Lysimachia ciliata
124 : 200: Itis Fraxinus
127 : 200: Itis Acer rubrum
132 : 200: Itis Iris versicolor
137 : 200: Itis Hypericum mutilum
142 : 200: Itis Quercus rubra

         Dataset Values  Validation Database values                        \
         scientificname Exact_Match         TaxonID Status Unacceptreason
144          Cichorieae      Non/no
58   Euphorbia maculata      Non/no
57              Senecio      Non/no
55      Ruppia maritima      Non/no
54             Plantago      Non/no


    Taxon_Rank Valid_TaxonID Valid_Name LSID
144
58
57
55
54